pool:
  vmImage: 'windows-latest'

variables:
  - group: sonarsource-build-variables

stages:
- stage: buildAndTests
  displayName: Build and run Unit tests
  jobs:
    - job: build
      pool:
       vmImage: 'windows-latest'
      displayName: 'Build, UT, analyze on SonarCloud'
      variables:
       solution: 'SonarScanner.MSBuild.sln'
       tfsProcessorSolution: 'SonarScanner.MSBuild.TFS.sln'
       buildPlatform: 'Any CPU'
       buildConfiguration: 'Release'
      steps:
      - checkout: self
      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet 5.8.1'
        inputs:
          versionSpec: '5.8.1'
      - task: DotNetCoreCLI@2
        displayName: Dotnet restore $(tfsProcessorSolution)
        inputs:
          command: 'restore'
          projects: '$(tfsProcessorSolution)'
          feedsToUse: 'select'
      - task: NuGetCommand@2
        displayName: 'NuGet restore TFS Processor'
        inputs:
          command: 'restore'
          restoreSolution: '$(tfsProcessorSolution)'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: 'Build $(tfsProcessorSolution)'
        inputs:
          command: 'build'
          projects: '$(tfsProcessorSolution)'
          arguments: '/m /p:DeployExtension=false /p:platform="$(BuildPlatform)" /p:configuration=$(BuildConfiguration) /p:ZipPackageCompressionLevel=normal'
      - task: NuGetCommand@2
        displayName: 'NuGet restore $(solution)'
        inputs:
          command: 'restore'
          restoreSolution: '$(solution)'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: Dotnet restore $(solution)
        inputs:
          command: 'restore'
          projects: '$(solution)'
          feedsToUse: 'select'
      - task: DotNetCoreCLI@2
        displayName: 'Build $(solution)'
        inputs:
          command: 'build'
          projects: '$(solution)'
          arguments: '/m /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /p:configuration=$(BuildConfiguration) /p:platform="$(BuildPlatform)"'
      - task: VSTest@2
        displayName: 'Run Unit Tests'
        inputs:
          testSelector: 'testAssemblies'
          testAssemblyVer2: |
            **\$(BuildConfiguration)\*test*.dll
            !**\obj\**
          searchFolder: '$(System.DefaultWorkingDirectory)'
          codeCoverageEnabled: true
